logging:
  level:
    io.vanillabp: DEBUG

server:
  port: 8088

spring:
  application:
    name: Demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./demodb.h2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2

workerId: test
