logging:
  level:
    io.vanillabp: TRACE
  pattern:
    level: "%mdc %5p"

server:
  port: 8080

spring:
  application:
    name: Demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./demodb.h2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    demo:
      change-log: classpath:liquibase/demo.yaml
      database-change-log-table: demo_changelog
      database-change-log-lock-table: demo_changeloglock
  h2:
    console:
      enabled: true
      path: /h2
    parameters:
      h2.long: BIGINT

workerId: demo
